// Show products a restaurant
GET http://localhost:3000/products?restaurant_id=3e37ee36-3088-42ad-ba33-5179f35355f3

###

GET http://localhost:3000/products/3e37ee36-3088-42ad-ba33-5179f35355f3?product_id=731c5fe0-5235-46c7-9bb0-1ced500bebe9

###

// Resgiter a product
POST http://localhost:3000/products/3e37ee36-3088-42ad-ba33-5179f35355f3
content-Type: application/json

{
  "productName": "Coca Cola",
  "productPrice": 7.50,
  "productCategory": "Refrigerantes",
  "productPhoto": "photo"
}

###

// Update a product
PUT http://localhost:3000/products/535aee82-9c22-41a8-a552-543d683145cf
content-Type: application/json

{
  "productName": "Coca Cola",
  "productPrice": 7.20,
  "productCategory": "Refrigerantes",
  "productPhoto": "photo"
}

###

// Delete a product
DELETE http://localhost:3000/products/535aee82-9c22-41a8-a552-543d683145cf
