// Show all restaurants
GET http://localhost:3000/restaurants

###

// Show a restaurant
GET http://localhost:3000/restaurants/c3eedb0d-6afe-4ce3-89a4-7174d32f5951

###

// Register a restaurant
POST http://localhost:3000/restaurants
content-Type: application/json

{
  "restaurantName": "Mc Donalds",
  "restaurantAddress": "Rua do Paraiso N°3367",
  "openingHours": "De Segunda a sexta das 09H às 21H e de Sabádo a Domingo das 11H às 23H",
  "restaurantPhoto": "photo"
}

###

// Update datas a restaurant
PUT http://localhost:3000/restaurants/c3eedb0d-6afe-4ce3-89a4-7174d32f5951
content-Type: application/json

{
  "restaurantName": "Mc Donalds",
  "restaurantAddress": "Rua do Paraiso N°3367",
  "openingHours": "De Segunda a sexta das 09H às 21H e de Sabádo a Domingo das 11H às 23H",
  "restaurantPhoto": "photo - 02"
}

###

// Delete a restaurant
DELETE http://localhost:3000/restaurants/c3eedb0d-6afe-4ce3-89a4-7174d32f5951
